issues:
  exclude-dirs:
    - pkg/mod           # Exclude dependency cache
    - opt/hostedtoolcache  # Exclude Go toolchain directory in GitHub Actions
  exclude-rules:
    - path: .*pkg/mod.*
      linters:
        - govet         # Adjust based on the linters you use
        - staticcheck
        - unused
    - path: .*opt/hostedtoolcache.*
      linters:
        - govet
        - staticcheck
        - unused
  
run:
  timeout: 5m

linters:
  exclusions:
    rules:
      - path: database/migrations.go
        text: "goose"
  enable:
    - unused
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - goimports
    - bodyclose
    - unconvert
    - gosec
    - noctx
    - gocritic
    - goconst
    - nilerr
    - contextcheck
    - whitespace