issues:
  exclude-rules:
    - path: .*pkg/mod.*
      linters:
        - typecheck
    - path: .*opt/hostedtoolcache.*
      linters:
        - typecheck
  
run:
  timeout: 5m

linters:
  exclusions:
    rules:
      - path: database/migrations.go
        text: "goose"
  enable:
    - unused
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - goimports
    - bodyclose
    - unconvert
    - gosec
    - noctx
    - gocritic
    - goconst
    - nilerr
    - contextcheck
    - whitespace