linters-settings:
  unused:
    check-exported: false
    exclude-use-default: false
run:
  timeout: 5m
  skip-dirs:
    - "**/vendor/**"
    - "**/pkg/mod/**"

linters:
  enable:
    - unused
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - goimports
    - bodyclose
    - unconvert
    - gosec
    - noctx
    - gocritic
    - goconst
    - nilerr
    - contextcheck
    - whitespace