issues:
  exclude-files:
    - '^/go/pkg/mod/.*'
    - '^/opt/hostedtoolcache/go/.*'
  
run:
  timeout: 5m


linters:
  exclusions:
    rules:
      - path: database/migrations.go
        text: "goose"
  enable:
    - unused
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - goimports
    - bodyclose
    - unconvert
    - gosec
    - noctx
    - gocritic
    - goconst
    - nilerr
    - contextcheck
    - whitespace