issues:
  exclude-rules:
    - path: '^/go/pkg/mod/.*'
      linters:
        - all
    - path: '^/opt/hostedtoolcache/go/.*'
      linters:
        - all
run:
  dir: .
  timeout: 5m


linters:
  enable:
    - unused
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - goimports
    - bodyclose
    - unconvert
    - gosec
    - noctx
    - gocritic
    - goconst
    - nilerr
    - contextcheck
    - whitespace