version: '3.8'

services:
  app:
    build: 
      context: .
      args:
        - GOPROXY=https://goproxy.cn,direct  # Используем китайское зеркало
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:parol@db:5432/main
    dns:
      - 8.8.8.8
      - 1.1.1.1
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=parol
      - POSTGRES_DB=main
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d main"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  postgres_data: